name: Run pre-commit check

on:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit:
    runs-on: self-hosted
    env:
      PIP_ROOT_USER_ACTION: ignore

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.8"

    - name: Set up Go 1.24.2
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.2"

    - name: Set up Node.js v22.14.0
      uses: actions/setup-node@v4
      with:
        node-version: "22.14.0"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Install Node.js dependencies
      run: |
        npm install
      working-directory: frontend

    - name: Run pre-commit
      run: pre-commit run --all-files
      continue-on-error: false
